# -*- coding: utf-8 -*-
"""허기페이스에서 f16gguf불러서 양자화 하는 코드

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kn6jZ-KRs70W8xpMPl_NM3BqNuYN-ddS
"""

from huggingface_hub import login, hf_hub_download, HfApi
import os

# 1. 로그인
login()

# 2. 모델 설정
REPO_ID = "lookarooka/Kambo-E2B-cm-v2"
F16_FILENAME = "merged-f16.gguf"
Q4_FILENAME = "Kambo-E2B-cm-v2-Q4_K_M.gguf"

# 3. 최신 CMake 방식으로 양자화 도구 빌드
print("🛠️ 최신 CMake 방식으로 양자화 도구를 빌드합니다...")
!rm -rf llama.cpp
!git clone -q https://github.com/ggml-org/llama.cpp
!mkdir -p llama.cpp/build
!cd llama.cpp/build && cmake .. -DGGML_CUDA=OFF > /dev/null 2>&1
!cd llama.cpp/build && make -j4 llama-quantize > /dev/null 2>&1

# 4. F16 파일 다운로드
print(f"\n📥 [{F16_FILENAME}] 다운로드...")
local_f16_path = hf_hub_download(repo_id=REPO_ID, filename=F16_FILENAME)

# 5. Q4 양자화 실행 (빌드된 경로: llama.cpp/build/bin/llama-quantize)
quantize_path = "./llama.cpp/build/bin/llama-quantize"
print(f"\n🗜️ 양자화 시작...")

if os.path.exists(quantize_path):
    !{quantize_path} {local_f16_path} {Q4_FILENAME} q4_k_m
else:
    print("❌ 에러: 양자화 프로그램(llama-quantize)을 찾을 수 없습니다!")

# 6. 결과물 업로드
if os.path.exists(Q4_FILENAME):
    print(f"\n☁️ 업로드 시작...")
    api = HfApi()
    api.upload_file(
        path_or_fileobj=Q4_FILENAME,
        path_in_repo=Q4_FILENAME,
        repo_id=REPO_ID
    )
    print(f"\n🎉 성공! 확인 주소: https://huggingface.co/{REPO_ID}/tree/main")
else:
    print("\n❌ 에러: 양자화된 파일이 생성되지 않았습니다.")

from huggingface_hub import HfApi, login

# 1. 로그인
login()

# 2. 저장소 이름
REPO_ID = "lookarooka/Kmbo-E2B-m-v1"
OLD_NAME = "gemma-4-e2b-it.Q4_K_M.gguf"
NEW_NAME = "Kmbo-E2B-m-v1-Q4_K_M.gguf"

# 3. 파일 이름 변경 및 삭제
api = HfApi()
print("🔄 파일 이름을 변경 중...")

# 새 이름으로 복사(업로드) -> 옛날 이름 삭제 순으로 진행
api.upload_file(
    path_or_fileobj=hf_hub_download(repo_id=REPO_ID, filename=OLD_NAME),
    path_in_repo=NEW_NAME,
    repo_id=REPO_ID
)
api.delete_file(path_in_repo=OLD_NAME, repo_id=REPO_ID)

print("🎉 완료! 이제 파일 이름이 예쁘게 바뀌었습니다.")